"use client";

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { formatEther, formatGwei } from "viem";
import type { ReceiptDataClient } from "./types";

function formatDate(d: Date | string): string {
  const date = typeof d === "string" ? new Date(d) : d;
  return date.toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "medium",
  });
}

export function generateReceiptPdf(data: ReceiptDataClient): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const margin = 20;
  let y = 20;

  // Header
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("RSK Receipt", margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text("Web3 Bookkeeper- Transaction Receipt for Accounting", margin, y);
  y += 15;

  doc.setTextColor(0, 0, 0);

  const tableData = [
    ["Transaction Hash", data.hash],
    ["Date & Time", formatDate(data.blockTimestamp)],
    ["Block Number", data.blockNumber],
    ["Status", data.status === "success" ? "Success" : "Reverted"],
    ["From", data.from],
    ["To", data.to ?? "Contract Creation"],
    ["Amount", `${data.valueFormatted} ${data.asset}`],
    ["USD Value (at tx time)", `$${data.usdValue.toFixed(2)}`],
  ];

  autoTable(doc, {
    startY: y,
    head: [["Field", "Value"]],
    body: tableData,
    theme: "plain",
    headStyles: {
      fillColor: [30, 30, 30],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    bodyStyles: {
      fontSize: 9,
    },
    columnStyles: {
      0: { cellWidth: 50, fontStyle: "bold" },
      1: { cellWidth: 120 },
    },
    margin: { left: margin, right: margin },
  });

  y = (doc.lastAutoTable?.finalY ?? y) + 15;

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Gas Details", margin, y);
  y += 7;

  const gasUsedBn = BigInt(data.gasUsed);
  const gasPriceBn = BigInt(data.gasPrice);
  const gasCostWei = gasUsedBn * gasPriceBn;
  const gasCostEth = formatEther(gasCostWei);

  autoTable(doc, {
    startY: y,
    body: [
      ["Gas Used", data.gasUsed],
      ["Effective Gas Price", `${formatGwei(gasPriceBn)} Gwei`],
      ["Total Gas Cost (rBTC)", gasCostEth],
    ],
    theme: "plain",
    bodyStyles: { fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 50, fontStyle: "bold" },
      1: { cellWidth: 120 },
    },
    margin: { left: margin, right: margin },
  });

  y = (doc.lastAutoTable?.finalY ?? y) + 15;

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text(
    `Generated by RSK-Receipts • explorer.rsk.co/tx/${data.hash} • Not financial advice`,
    margin,
    doc.internal.pageSize.getHeight() - 10
  );

  const filename = `rsk-receipt-${data.hash.slice(0, 10)}.pdf`;
  doc.save(filename);
}
